server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost #consul我们部署在本机，用cmd命令行直接开启consul服务端，就不需要和eureka一样再新建consul服务端模块了
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
